model:
  name: bert4rec
  save_name: bert4rec_CE

  params:
    model_params:
      block_count: 2
      head_count: 2
      max_seq_len: 200
      hidden_size: 312
      dropout_rate: 0.15
      loss_type: CE # CE, BCE, SCE
      loss_sample_count: Null
    training_params:
      embedding_dim: 312
      learning_rate: 0.001
      batch_size: 8
      num_workers: 4
      max_epochs: 100