model:
  name: bert4rec

  params:
    block_count: 2
    head_count: 4
    max_sequence_length: 20
    hidden_size: 312
    learning_rate: 0.002
    dropout_rate: 0.15

    batch_size: 512
    num_workers: 4
    max_epochs: 100
    embedding_dim: 312