model:
  name: sasrec
  save_name: sasrec_CE_777

  params:
    model_params:
      block_count: 1
      head_count: 2
      max_seq_len: 50
      hidden_size: 1024
      dropout_rate: 0.2
      loss_type: CE # CE, BCE, SCE
      loss_sample_count: 200
      n_buckets: 443
      bucket_size_x: 443
      bucket_size_y: 512
      mix_x: true
    training_params:
      embedding_dim: 1024
      learning_rate: 0.00001
      weight_decay: 0.00006
      batch_size: 256
      num_workers: 4
      patience: 4
      max_epochs: 2
      precision: bf16-mixed
