model:
  name: sasrec
  save_name: sasrec_BCE

  params:
    model_params:
      block_count: 2
      head_count: 2
      max_seq_len: 100
      hidden_size: 312
      dropout_rate: 0.15
      loss_type: BCE # CE, BCE, SCE
      loss_sample_count: 500
      n_buckets: 443
      bucket_size_x: 443
      bucket_size_y: 512
      mix_x: true
    training_params:
      embedding_dim: 312
      learning_rate: 0.001
      batch_size: 64
      num_workers: 4
      patience: 4
      max_epochs: 20
      precision: null #default 32, bf16-mixed
