workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "schedule"

image: "${CI_REGISTRY_IMAGE}:${VERSION}_py39"

variables:
  VERSION: "0.0.5"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

.setup_env: &setup_env
  - pip install -q --upgrade pip wheel poetry==1.5.1 lightfm

.install_replay: &install_replay
  before_script:
    - *setup_env
    - poetry install

cache: &global_cache
  key: ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}
  paths:
    - .cache/pip
    - .cache/pypoetry
  policy: pull

stages:
  - resolve
  - code_quality
  - test

resolve-job:
  stage: resolve
  cache:
    <<: *global_cache
    policy: push
  script:
    - *setup_env
    - poetry --version
    - pip --version
    - poetry install
    - dependencies="${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_dependencies.txt"
    - dependencies=$(echo ${dependencies} | sed -e 's/[^0-9a-zA-Z.-]/_/g') # removed invalid characters
    - pip list > ${dependencies}
  artifacts:
    paths:
      - poetry.lock
      - ${dependencies}
    expire_in: 2 week

pylint-job:
  <<: *install_replay
  stage: code_quality
  script:
    - pylint replay

pycodestyle-job:
  <<: *install_replay
  stage: code_quality
  script:
    - pycodestyle replay tests

sphinx-job:
  <<: *install_replay
  stage: code_quality
  script:
    - make -C docs clean html

test-job:
  <<: *install_replay
  stage: test
  script:
    - pytest
