workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

image: "${CI_REGISTRY_IMAGE}:${VERSION}_py39"

variables:
  VERSION: "0.0.10"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  RUNNER: amazme-1

.wrapper_install: &wrapper_install
  - ./poetry_wrapper.sh ${WRAPPER_ARGS} sync ${WRAPPER_EXTRAS} 

.install_conditionals: &install_conditionals
  - ./poetry_wrapper.sh --generate
  - eval $(poetry env activate)
  - pip install -q --upgrade onnx openvino optuna hnswlib fixed-install-nmslib

.install_experimental_replay_all_extras: &install_experimental_replay_all_extras
  variables:
    WRAPPER_ARGS: --experimental
  before_script:
    - *wrapper_install
    - *install_conditionals

stages:
  - code_quality
  - test_core
  - test_conditional
  - test_torch
  - test_spark
  - test_spark_torch
  - test_models
  - test_experimental
  - merge coverage
  - examples
  - build packages

ruff:
  <<: *install_experimental_replay_all_extras
  stage: code_quality
  script:
    - poetry run ruff check .
  tags:
    - ${RUNNER}

black:
  <<: *install_experimental_replay_all_extras
  stage: code_quality
  script:
    - poetry run black . --check --diff
  tags:
    - ${RUNNER}

poetry-check:
  <<: *install_experimental_replay_all_extras
  stage: code_quality
  script:
    - ./poetry_wrapper.sh check
    - ./poetry_wrapper.sh --experimental check
  tags:
    - ${RUNNER}

toml-sort:
  <<: *install_experimental_replay_all_extras
  stage: code_quality
  script:
    - ./poetry_wrapper.sh --generate
    - poetry run toml-sort --check pyproject.toml
    - ./poetry_wrapper.sh --experimental --generate
    - poetry run toml-sort --check pyproject.toml
  tags:
    - ${RUNNER}

sphinx-job:
  <<: *install_experimental_replay_all_extras
  stage: code_quality
  script:
    - make -C docs clean html
  tags:
    - ${RUNNER}

.pytest_template: &pytest_template
  image: ${image}
  tags:
    - ${RUNNER}
  needs: ["ruff", "black", "poetry-check", "sphinx-job"]
  before_script:
    - export REPLAY_SPARK_CORE_COUNT=4
    - export REPLAY_SPARK_MEMORY=16
    - *wrapper_install
  parallel:
    matrix:
      - image:
        - "${CI_REGISTRY_IMAGE}:${VERSION}_py39"
        - "${CI_REGISTRY_IMAGE}:${VERSION}_py310"
        - "${CI_REGISTRY_IMAGE}:${VERSION}_py311"

pytest-core:
  <<: *pytest_template
  stage: test_core
  script:
    - ./poetry_wrapper.sh --generate
    - poetry run pytest -m core tests/ --ignore=tests/experimental
    - mv .coverage .coverage_core_${image:(-4)}
  artifacts:
    paths:
      - .coverage_core_${image:(-4)}
    expire_in: 1 day

pytest-conditional:
  <<: *pytest_template
  stage: test_conditional
  variables:
    WRAPPER_ARGS: --experimental
  script:
    - *install_conditionals
    - ./poetry_wrapper.sh --generate
    - poetry run pytest -m conditional tests/ --ignore=tests/experimental
    - mv .coverage .coverage_conditional_${image:(-4)}
  artifacts:
    paths:
      - .coverage_conditional_${image:(-4)}
    expire_in: 1 day

pytest-torch:
  <<: *pytest_template
  stage: test_torch
  variables:
    WRAPPER_EXTRAS: -E torch
  script:
    - ./poetry_wrapper.sh --generate
    - poetry run pytest -m "not spark and not experimental and not conditional" tests/ --ignore=tests/experimental
    - mv .coverage .coverage_torch_${image:(-4)}
  artifacts:
    paths:
      - .coverage_torch_${image:(-4)}
    expire_in: 1 day

pytest-spark:
  <<: *pytest_template
  stage: test_spark
  variables:
    WRAPPER_EXTRAS: -E spark
  script:
    - ./poetry_wrapper.sh --generate
    - poetry run pytest -m "not torch and not experimental and not conditional" tests/ --ignore=tests/experimental --ignore=tests/models
    - mv .coverage .coverage_spark_${image:(-4)}
  artifacts:
    paths:
      - .coverage_spark_${image:(-4)}
    expire_in: 1 day

pytest-spark-and-torch:
  <<: *pytest_template
  stage: test_spark_torch
  variables:
    WRAPPER_EXTRAS: -E torch -E spark
  script:
    - ./poetry_wrapper.sh --generate
    - poetry run pytest -m "not experimental and not conditional" --ignore=replay/models/nn/sequential/compiled --ignore=replay/experimental --ignore=tests/experimental --ignore=tests/models
    - mv .coverage .coverage_spark_and_torch_${image:(-4)}
  artifacts:
    paths:
      - .coverage_spark_and_torch_${image:(-4)}
    expire_in: 1 day

pytest-models:
  <<: *pytest_template
  stage: test_models
  variables:
    WRAPPER_EXTRAS: -E torch -E spark
  script:
    - ./poetry_wrapper.sh --generate
    - poetry run pytest -m "not experimental and not conditional" tests/models --ignore=replay/experimental --ignore=tests/experimental
    - mv .coverage .coverage_models_${image:(-4)}
  artifacts:
    paths:
      - .coverage_models_${image:(-4)}
    expire_in: 1 day

pytest-experimental:
  <<: *pytest_template
  stage: test_experimental
  variables:
    WRAPPER_ARGS: --experimental
  script:
    - *install_conditionals
    - ./poetry_wrapper.sh --generate
    - poetry run pytest -m "experimental"
    - mv .coverage .coverage_experimental_${image:(-4)}
  artifacts:
    paths:
      - .coverage_experimental_${image:(-4)}
    expire_in: 1 day

merge-coverage:
  stage: merge coverage
  variables: 
    WRAPPER_EXTRAS: --only dev
  before_script:
    - *wrapper_install
  script:
    - ./poetry_wrapper.sh --generate
    - poetry run coverage combine .coverage_core_${image:(-4)} .coverage_conditional_${image:(-4)} .coverage_spark_${image:(-4)} .coverage_torch_${image:(-4)} .coverage_spark_and_torch_${image:(-4)} .coverage_models_${image:(-4)} .coverage_experimental_${image:(-4)}
    - poetry run coverage xml
    - poetry run coverage report -m --fail-under=100
  needs: ["pytest-core", "pytest-conditional", "pytest-torch", "pytest-spark", "pytest-spark-and-torch", "pytest-models", "pytest-experimental"]
  tags:
    - ${RUNNER}
  parallel:
    matrix:
      - image:
        - "${CI_REGISTRY_IMAGE}:${VERSION}_py39"
        - "${CI_REGISTRY_IMAGE}:${VERSION}_py310"
        - "${CI_REGISTRY_IMAGE}:${VERSION}_py311"
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

examples-execute-job:
  before_script:
    - *wrapper_install
  rules:
    - when: never
  stage: examples
  script:
    - export EXAMPLES_EXCLUDE=02_models_comparison.ipynb,06_item2item_recommendations.ipynb
    - cd examples
    - for i in *.ipynb; do [[ ! "$EXAMPLES_EXCLUDE" =~ "$i" ]] && jupyter nbconvert --to notebook --execute $i; done

build-production-package:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build packages
  tags:
    - ${RUNNER}
  script:
    - export PACKAGE_SUFFIX=.dev${CI_JOB_ID}
    - echo $PACKAGE_SUFFIX
    - ./poetry_wrapper.sh --generate
    - poetry version
    - poetry config repositories.replay ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --build -r replay -u gitlab-ci-token -p ${CI_JOB_TOKEN}


build-experimental-package:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build packages
  tags:
    - ${RUNNER}
  script:
    - export PACKAGE_SUFFIX=.preview${CI_JOB_ID}
    - echo $PACKAGE_SUFFIX
    - ./poetry_wrapper.sh --experimental --generate
    - poetry version
    - poetry config repositories.replay ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --build -r replay -u gitlab-ci-token -p ${CI_JOB_TOKEN}
