name: Build Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main, refactoring]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      c
      - name: Install full package
        run: |
          ./uv_wrapper.sh --experimental --generate
          uv sync --group dev --no-cache
          uv pip install --upgrade onnx onnxscript openvino optuna hnswlib fixed-install-nmslib git+https://github.com/daviddavo/lightfm.git@f0eb500ead54ab65eb8e1b3890337a7223a35114 --no-cache-dir
      - name: Build docs
        run: |
          uv run make -C docs clean html
