name: Build Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main, refactoring]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: "3.10"
      - name: clear_poetry_cache
        run: poetry cache clear PyPI --all
      - name: install_experimental_dev_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          experimental: "true"
          with-dev: "true"
      - name: install_conditionals
        uses: ./.github/actions/install-conditionals
      - name: Build docs
        run: |
          eval "$(poetry env activate)"
          make -C docs clean html
