name: Deploy Docs to Pages

on:
  push:
    branches: [release]
    tags:
      - 'v*.*.*'
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install full package
        run: |
          curl -LsSf https://astral.sh/uv/0.10.7/install.sh | sh
          uv pip install --system --no-cache --upgrade pip wheel
          uv cache prune --ci
          ./uv_wrapper.sh --experimental --generate
          uv sync --group dev --no-cache
          uv pip install --upgrade onnx onnxscript openvino optuna hnswlib fixed-install-nmslib git+https://github.com/daviddavo/lightfm.git@f0eb500ead54ab65eb8e1b3890337a7223a35114 --no-cache-dir
      - name: Build docs
        run: |
          uv run make -C docs clean html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
