name: Deploy Docs to Pages

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - release
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check_tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Check release tag
    runs-on: ubuntu-latest
    outputs:
      has_tag: ${{ steps.check.outputs.has_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Check tag presence
        id: check
        shell: bash
        run: |
          TAG="$(git tag --points-at "${{ github.event.workflow_run.head_sha }}" | grep '^v')"
          echo "Found tag: $TAG"
          echo "has_tag=true" >> "$GITHUB_OUTPUT"

  deploy_docs:
    needs: check_tag
    if: needs.check_tag.outputs.has_tag == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install full package
        run: |
          pip install --upgrade pip wheel poetry==2.2.1 poetry-dynamic-versioning --no-cache-dir
          poetry cache clear PyPI --all
          ./poetry_wrapper.sh --experimental --generate
          eval $(poetry env activate)
          poetry sync --with dev --no-cache
          pip install --upgrade onnx onnxscript openvino optuna hnswlib fixed-install-nmslib git+https://github.com/daviddavo/lightfm.git@f0eb500ead54ab65eb8e1b3890337a7223a35114 --no-cache-dir
      - name: Build docs
        run: |
          eval $(poetry env activate)
          make -C docs clean html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
