name: CI Pipeline

on:
  push:
    branches: [main, 'release/**']
  pull_request:
    branches: [main, refactoring]
  workflow_dispatch:

jobs:
  static_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: "3.10"
      - name: install_dev_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          with-dev: "true"
      - name: clear_poetry_cache
        run: |
          eval "$(poetry env activate)"
          poetry cache clear PyPI --all
      - name: ruff
        run: poetry run ruff check .
      - name: black
        run: poetry run black . --check --diff
      - name: poetry-check
        run: |
          ./poetry_wrapper.sh check
          ./poetry_wrapper.sh --experimental check
      - name: toml-sort
        run: |
          ./poetry_wrapper.sh --generate
          poetry run toml-sort --check pyproject.toml
          ./poetry_wrapper.sh --experimental --generate
          poetry run toml-sort --check pyproject.toml

  pytest_core:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_core_dependencies
        uses: ./.github/actions/install-poetry-deps
      - name: prepare_pyproject_for_tests
        run: ./poetry_wrapper.sh --generate
      - name: pytest
        run: |
          poetry run pytest -m core tests/ --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_core_${{ matrix.python-version }}
      - name: upload_coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage_core_${{ matrix.python-version }}
          path: coverage_core_${{ matrix.python-version }}

  pytest_conditional:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_experimental_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          experimental: "true"
      - name: install_pyspark
        uses: ./.github/actions/install-pyspark
      - name: install_conditionals
        uses: ./.github/actions/install-conditionals
      - name: prepare_pyproject_for_tests
        run: ./poetry_wrapper.sh --generate
      - name: pytest
        run: |
          poetry run pytest -m conditional tests/ --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_conditional_${{ matrix.python-version }}
      - name: upload_coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage_conditional_${{ matrix.python-version }}
          path: coverage_conditional_${{ matrix.python-version }}

  pytest_torch:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_base_dependencies
        uses: ./.github/actions/install-poetry-deps
      - name: install_torch_cpu
        uses: ./.github/actions/install-torch-cpu
      - name: pytest
        run: |
          poetry run pytest -m "not spark and not experimental and not conditional" tests/ --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_torch_${{ matrix.python-version }}
      - name: upload_coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage_torch_${{ matrix.python-version }}
          path: coverage_torch_${{ matrix.python-version }}

  pytest_spark:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_spark_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          extras: "spark"
      - name: install_pyspark
        uses: ./.github/actions/install-pyspark
      - name: pytest
        run: |
          poetry run pytest -m "not torch and not experimental and not conditional" tests/ --ignore=tests/experimental --ignore=tests/models --ignore=tests/conditional
          mv .coverage coverage_spark_${{ matrix.python-version }}
      - name: upload_coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage_spark_${{ matrix.python-version }}
          path: coverage_spark_${{ matrix.python-version }}

  pytest_spark_torch:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_spark_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          extras: "spark"
      - name: install_pyspark
        uses: ./.github/actions/install-pyspark
      - name: install_torch_cpu
        uses: ./.github/actions/install-torch-cpu
      - name: pytest
        run: |
          poetry run pytest -m "not experimental and not conditional" --ignore=replay/models/nn/sequential/compiled --ignore=replay/experimental --ignore=tests/experimental --ignore=tests/models --ignore=tests/conditional
          mv .coverage coverage_spark_and_torch_${{ matrix.python-version }}
      - name: upload_coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage_spark_and_torch_${{ matrix.python-version }}
          path: coverage_spark_and_torch_${{ matrix.python-version }}

  pytest_experimental:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_experimental_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          experimental: "true"
      - name: install_pyspark
        uses: ./.github/actions/install-pyspark
      - name: install_conditionals
        uses: ./.github/actions/install-conditionals
      - name: pytest
        run: |
          poetry run pytest -m "experimental" tests/
          mv .coverage coverage_experimental_${{ matrix.python-version }}
      - name: upload_coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage_experimental_${{ matrix.python-version }}
          path: coverage_experimental_${{ matrix.python-version }}

  pytest_models:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_spark_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          extras: "spark"
      - name: install_pyspark
        uses: ./.github/actions/install-pyspark
      - name: install_torch_cpu
        uses: ./.github/actions/install-torch-cpu
      - name: pytest
        run: |
          poetry run pytest -m "not experimental and not conditional" tests/models --ignore=replay/experimental --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_models_${{ matrix.python-version }}
      - name: upload_coverage
        uses: actions/upload-artifact@v6
        with:
          name: coverage_models_${{ matrix.python-version }}
          path: coverage_models_${{ matrix.python-version }}

  merge_coverage:
    needs: [pytest_core, pytest_conditional, pytest_torch, pytest_spark, pytest_spark_torch, pytest_models, pytest_experimental]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_only_dev_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          only-dev: "true"
      - name: download_coverage_reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage_*
          merge-multiple: true
      - name: combine_coverage
        run: |
          poetry run coverage combine coverage_core_${{ matrix.python-version }} coverage_conditional_${{ matrix.python-version }} coverage_torch_${{ matrix.python-version }} coverage_spark_${{ matrix.python-version }} coverage_spark_and_torch_${{ matrix.python-version }} coverage_models_${{ matrix.python-version }} coverage_experimental_${{ matrix.python-version }}
          poetry run coverage report --fail-under=100
          poetry run coverage xml

  build_production:
    needs: merge_coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: "3.10"
      - name: install_spark_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          extras: "spark"
      - name: install_torch_cpu
        uses: ./.github/actions/install-torch-cpu
      - name: build
        run: |
          export PACKAGE_SUFFIX=.dev
          poetry build

  build_experimental:
    needs: merge_coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: "3.10"
      - name: install_experimental_dev_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          experimental: "true"
          with-dev: "true"
      - name: build
        run: |
          export PACKAGE_SUFFIX=.preview
          poetry build
