name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main, refactoring]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  static_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup
      - name: Install full package
        run: ./uv_wrapper.sh sync --group dev --no-cache
      - name: ruff
        run: ./uv_wrapper.sh run ruff check .
      - name: black
        run: ./uv_wrapper.sh run black . --check --diff
      - name: toml-sort
        run: |
          ./uv_wrapper.sh run toml-sort --check pyproject.toml
          ./uv_wrapper.sh --experimental run toml-sort --check pyproject.toml

  pytest_core:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core package
        run: ./uv_wrapper.sh sync
      - name: pytest
        run: |
          ./uv_wrapper.sh run pytest -m core tests/ --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_core_${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_core_${{ matrix.python-version }}
          path: coverage_core_${{ matrix.python-version }}
  
  pytest_conditional:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install conditional package
        run: |
          ./uv_wrapper.sh --experimental sync --group dev --no-cache
          ./uv_wrapper.sh --experimental pip install -q --upgrade onnx onnxscript openvino optuna hnswlib fixed-install-nmslib git+https://github.com/daviddavo/lightfm.git@f0eb500ead54ab65eb8e1b3890337a7223a35114 --no-cache-dir
      - name: pytest
        run: |
          ./uv_wrapper.sh run pytest -m conditional tests/ --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_conditional_${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_conditional_${{ matrix.python-version }}
          path: coverage_conditional_${{ matrix.python-version }}

  pytest_torch:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install torch package
        run: ./uv_wrapper.sh sync --extra torch --no-cache
      - name: pytest
        run: |
          ./uv_wrapper.sh run pytest -m "not spark and not experimental and not conditional" tests/ --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_torch_${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_torch_${{ matrix.python-version }}
          path: coverage_torch_${{ matrix.python-version }}

  pytest_spark:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install spark package
        run: ./uv_wrapper.sh sync --extra spark --no-cache
      - name: pytest
        run: |
          uv run pytest -m "not torch and not experimental and not conditional" tests/ --ignore=tests/experimental --ignore=tests/models --ignore=tests/conditional
          mv .coverage coverage_spark_${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_spark_${{ matrix.python-version }}
          path: coverage_spark_${{ matrix.python-version }}

  pytest_spark_torch:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install full package
        run: ./uv_wrapper.sh sync --extra spark --extra torch --no-cache
      - name: pytest
        run: |
          ./uv_wrapper.sh run pytest -m "not experimental and not conditional" --ignore=replay/models/nn/sequential/compiled --ignore=replay/experimental --ignore=tests/experimental --ignore=tests/models --ignore=tests/conditional
          mv .coverage coverage_spark_and_torch_${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_spark_and_torch_${{ matrix.python-version }}
          path: coverage_spark_and_torch_${{ matrix.python-version }}

  pytest_experimental:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install experimental package
        run: |
          ./uv_wrapper.sh --experimental sync --no-cache
          ./uv_wrapper.sh --experimental install -q --upgrade onnx onnxscript openvino optuna hnswlib fixed-install-nmslib git+https://github.com/daviddavo/lightfm.git@f0eb500ead54ab65eb8e1b3890337a7223a35114 --no-cache-dir
      - name: pytest
        run: |
          ./uv_wrapper.sh --experimental run pytest -m "experimental" tests/
          mv .coverage coverage_experimental_${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_experimental_${{ matrix.python-version }}
          path: coverage_experimental_${{ matrix.python-version }}

  pytest_models:
    needs: static_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install full package
        run: ./uv_wrapper.sh sync --extra spark --extra torch --no-cache
      - name: pytest
        run: |
          ./uv_wrapper.sh run pytest -m "not experimental and not conditional" tests/models --ignore=replay/experimental --ignore=tests/experimental --ignore=tests/conditional
          mv .coverage coverage_models_${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_models_${{ matrix.python-version }}
          path: coverage_models_${{ matrix.python-version }}

  merge_coverage:
    needs: [pytest_core, pytest_conditional, pytest_torch, pytest_spark, pytest_spark_torch, pytest_models, pytest_experimental]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install only dev package
        run: ./uv_wrapper.sh sync --only-dev --no-cache
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage_*
          merge-multiple: true
      - name: Combine coverage
        run: |
          ./uv_wrapper.sh --generate
          uv run coverage combine coverage_core_${{ matrix.python-version }} coverage_conditional_${{ matrix.python-version }} coverage_torch_${{ matrix.python-version }} coverage_spark_${{ matrix.python-version }} coverage_spark_and_torch_${{ matrix.python-version }} coverage_models_${{ matrix.python-version }} coverage_experimental_${{ matrix.python-version }}
          uv run coverage report --fail-under=100
          uv run coverage xml

  build_production:
    needs: merge_coverage
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup
      - name: Install production package
        run: ./uv_wrapper.sh sync --extra torch --extra spark --no-cache
      - name: Build
        run: |
          export PACKAGE_SUFFIX=.dev
          uv build

  build_experimental:
    needs: merge_coverage
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup
      - name: Install full package
        run: ./uv_wrapper.sh --experimental sync --group dev --no-cache
      - name: Build
        run: |
          export PACKAGE_SUFFIX=.preview
          uv build
