name: Publish to PyPI

# Run publish only on release branch after finished CI 
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: ['release/**']
  
  workflow_dispatch:

jobs:
  check_tag:
    if : ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/check_release_tag.yml
    with:
      sha: ${{ github.event.workflow_run.head_sha }}

  publish_experimental:
    needs: check_tag
    if: needs.check_tag.outputs.has_tag == 'true'
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    environment:
        name: release
        url: https://pypi.org/p/replay-rec

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: "3.10"

      - name: clear_poetry_cache
        run: poetry cache clear PyPI --all

      - name: install_experimental_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          experimental: "true"

      - name: build_experimental
        run: |
          export PACKAGE_SUFFIX=.preview
          poetry build

      - name: publish_experimental
        uses: pypa/gh-action-pypi-publish@release/v1

  publish_production:
    needs: check_tag
    if: needs.check_tag.outputs.has_tag == 'true'
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    environment:
        name: release
        url: https://pypi.org/p/replay-rec

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: "3.10"

      - name: clear_poetry_cache
        run: poetry cache clear PyPI --all

      - name: install_production_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          extras: "spark"
      - name: install_torch_cpu
        uses: ./.github/actions/install-torch-cpu

      - name: build_production
        run: |
          poetry build

      - name: publish_production
        uses: pypa/gh-action-pypi-publish@release/v1
