name: Publish to test PyPI

on: 
  workflow_dispatch:

jobs:
  
  publish_test:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    environment:
        name: testpypi
        url: https://test.pypi.org/p/replay-rec

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: ci_setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: "3.10"

      - name: clear_poetry_cache
        run: poetry cache clear PyPI --all
      - name: install_dev_dependencies
        uses: ./.github/actions/install-poetry-deps
        with:
          with-dev: "true"

      - name: build
        run: |
          export PACKAGE_SUFFIX=.preview
          echo $PACKAGE_SUFFIX
          poetry build

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          repository-url: https://test.pypi.org/legacy/
