name: Publish to test PyPI

on: 
  workflow_dispatch:

jobs:
  
  publish_test:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    environment:
        name: testpypi
        url: https://test.pypi.org/p/replay-rec

    steps:
      - uses: ./.github/actions/ci-setup

      - name: Install full package
        run: ./uv_wrapper.sh sync --group dev

      - name: Build
        run: |
          export PACKAGE_SUFFIX=.preview
          echo $PACKAGE_SUFFIX
          ./uv_wrapper.sh build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          repository-url: https://test.pypi.org/legacy/
