name: Publish to PyPI

# Run publish only on release branch after finished CI 
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: ['release/**']
  
  workflow_dispatch:

jobs:
  check_tag:
    if : ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/check_release_tag.yml
    with:
      sha: ${{ github.event.workflow_run.head_sha }}

  publish_experimental:
    needs: check_tag
    if: needs.check_tag.outputs.has_tag == 'true'
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    environment:
        name: release
        url: https://pypi.org/p/replay-rec

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install experimental package
        run: |
          pip install --upgrade pip wheel poetry==2.2.1 poetry-dynamic-versioning --no-cache-dir
          ./poetry_wrapper.sh --experimental --generate
          eval $(poetry env activate)
          poetry cache clear PyPI --all
          poetry sync --no-cache

      - name: Build Experimental
        run: |
          export PACKAGE_SUFFIX=.preview
          poetry build

      - name: Publish Experimental
        uses: pypa/gh-action-pypi-publish@release/v1

  publish_production:
    needs: check_tag
    if: needs.check_tag.outputs.has_tag == 'true'
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    environment:
        name: release
        url: https://pypi.org/p/replay-rec

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install production package
        run: |
          pip install --upgrade pip wheel poetry==2.2.1 poetry-dynamic-versioning --no-cache-dir
          ./poetry_wrapper.sh --generate
          eval $(poetry env activate)
          poetry cache clear PyPI --all
          poetry sync -E torch -E spark --no-cache

      - name: Build Production
        run: |
          poetry build

      - name: Publish Production
        uses: pypa/gh-action-pypi-publish@release/v1
